# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0007_auto_20160911_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('form_pdf', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date_of_physical', models.DateField()),
                ('page_1_received', models.BooleanField(default=False)),
                ('page_2_received', models.BooleanField(default=False)),
                ('ins_card_received', models.BooleanField(default=False)),
                ('page_1_incomplete', models.BooleanField(default=False)),
                ('page_2_incomplete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_forms', to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
