# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('certification_type', models.IntegerField(choices=[(3, 'WFR'), (4, 'EMT'), (1, 'CPR'), (2, 'WFA'), (5, 'Driver')], default=2)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('source', models.CharField(default='SOLO', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
