# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Derp',
            fields=[
                ('herp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Herp')),
                ('derp_name', models.CharField(max_length=255)),
            ],
            bases=('person.herp',),
        ),
        migrations.CreateModel(
            name='Yo',
            fields=[
                ('herp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Herp')),
                ('yo_name', models.CharField(max_length=255)),
            ],
            bases=('person.herp',),
        ),
    ]
