# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derp',
            name='herp_ptr',
        ),
        migrations.RemoveField(
            model_name='yo',
            name='herp_ptr',
        ),
        migrations.DeleteModel(
            name='Derp',
        ),
        migrations.DeleteModel(
            name='Herp',
        ),
        migrations.DeleteModel(
            name='Yo',
        ),
    ]
