# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0005_auto_20160910_2344'),
        ('person', '0002_auto_20160911_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='USA', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Person')),
                ('harvard_email', models.CharField(blank=True, max_length=255, null=True)),
                ('huid', models.IntegerField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.IntegerField(blank=True, choices=[(1, b'Quincy')], null=True)),
                ('current_student_type', models.IntegerField(choices=[(1, b'Fopper'), (3, b'Leader'), (2, b'Trainee')])),
                ('dorm', models.IntegerField(blank=True, choices=[(1, b'Mower')], null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('school_type', models.IntegerField(choices=[(1, b'Public'), (2, b'Private')], default=1)),
                ('height_feet', models.CharField(blank=True, max_length=255, null=True)),
                ('height_inches', models.CharField(blank=True, max_length=255, null=True)),
                ('tshirt_size', models.IntegerField(choices=[(4, b'Large'), (5, b'Extra Large'), (2, b'Small'), (3, b'Medium'), (1, b'Extra Small')], default=4)),
                ('gender', models.IntegerField(choices=[(1, b'Male'), (3, b'Other'), (2, b'Female')])),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('significant_allergy', models.BooleanField(default=False)),
                ('allergy_info', models.TextField(blank=True, null=True)),
                ('food_restrictions', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='Fopper',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Student')),
                ('accepted', models.BooleanField(default=True)),
                ('harvard_financial_aid', models.BooleanField(default=False)),
                ('requests_fop_financial_aid', models.BooleanField(default=False)),
                ('receives_fop_financial_aid', models.BooleanField(default=False)),
                ('accepts_release_of_information', models.BooleanField(default=False)),
                ('swimming_ability', models.IntegerField(blank=True, choices=[(3, b'Competetive'), (1, b'None'), (2, b'Casual')], null=True)),
                ('preferred_backpacking_difficulty', models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True)),
                ('preferred_switch_difficulty', models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True)),
                ('preferred_service_difficulty', models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True)),
                ('first_choice', models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True)),
                ('second_choice', models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True)),
                ('third_choice', models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True)),
                ('fourth_choice', models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True)),
                ('fifth_choice', models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='trip.Trip')),
            ],
            options={
                'abstract': False,
            },
            bases=('person.student',),
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Student')),
                ('is_sc', models.BooleanField(default=False)),
                ('switch', models.BooleanField(default=False)),
                ('preferred_difficulty', models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True)),
                ('preferred_trip_type', models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('was_fopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='person.Fopper')),
            ],
            options={
                'abstract': False,
            },
            bases=('person.student',),
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='person.Student'),
        ),
    ]
