# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20160911_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='do_not_solicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='special_donot',
            field=models.BooleanField(default=False),
        ),
    ]
