# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20160911_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='special_donot',
            new_name='special_donor',
        ),
        migrations.AlterField(
            model_name='fopper',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='trip.Trip'),
        ),
    ]
