# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20160911_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='fopper',
            name='service_alt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fopper',
            name='switch_alt',
            field=models.BooleanField(default=False),
        ),
    ]
