# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20160911_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='switch',
            new_name='trained_service',
        ),
        migrations.AddField(
            model_name='leader',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='cc_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='trained_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leader',
            name='year_trained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='years_on_steering_committee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='years_on_summer_staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
