# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20160911_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='fopper',
            name='allergy',
            field=models.IntegerField(default=0, help_text=b'This is just for development of the algorithm'),
        ),
    ]
