# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='water_on_trail_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='amc_maintained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='can_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='has_good_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='has_platforms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='has_privy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='reservation_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='sleeping_space_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='water_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='has_good_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trail',
            name='water_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='campsite_and_water',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='dropoff_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='pickup_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='views_and_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='water_on_trail',
            field=models.BooleanField(default=False),
        ),
    ]
