# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_auto_20160910_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_type',
            field=models.IntegerField(choices=[(6, 'Pick Up'), (5, 'Service'), (4, 'Canoe'), (1, 'Drop Off'), (3, 'Switch'), (2, 'Hike')], default=2),
        ),
    ]
