# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0004_day_day_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='is_national_forest',
            field=models.BooleanField(default=False),
        ),
    ]
