# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('student', '0002_leader'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='leaders',
            field=models.ManyToManyField(null=True, to='student.Leader'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.IntegerField(null=True),
        ),
    ]
