# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20160910_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='leaders',
            field=models.ManyToManyField(to='student.Leader'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
