# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20160910_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True),
        ),
        # migrations.AlterField(
        #     model_name='trip',
        #     name='leaders',
        #     field=models.ManyToManyField(related_name='trips', to='student.Leader'),
        # ),
    ]
