# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20160910_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='basecamp',
            field=models.IntegerField(blank=True, choices=[(1, 'Maine'), (2, 'New Hampshire')], null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='emergency_cell_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='liason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='luggage_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_people',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='menu',
            field=models.IntegerField(choices=[(3, b'Nut Free'), (1, b'Standard')], default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='pick_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='plb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='sleeping_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
    ]
