# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_trip_leaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pick_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
