# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_auto_20160911_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='daily_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
