# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('house', models.IntegerField(blank=True, choices=[(1, 'Quincy')], null=True)),
                ('dorm', models.IntegerField(blank=True, choices=[(1, 'Mower')], null=True)),
                ('is_sc', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
