# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_fopper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='USA', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.IntegerField(blank=True, choices=[(1, 'Quincy')], null=True)),
                ('dorm', models.IntegerField(blank=True, choices=[(1, 'Mower')], null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('school_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1)),
                ('height_feet', models.CharField(blank=True, max_length=255, null=True)),
                ('height_inches', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('huid', models.IntegerField()),
                ('tshirt_size', models.IntegerField(choices=[(4, 'Large'), (5, 'Extra Large'), (2, 'Small'), (3, 'Medium'), (1, 'Extra Small')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='USA', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.IntegerField(blank=True, choices=[(1, 'Quincy')], null=True)),
                ('dorm', models.IntegerField(blank=True, choices=[(1, 'Mower')], null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('school_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1)),
                ('height_feet', models.CharField(blank=True, max_length=255, null=True)),
                ('height_inches', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('huid', models.IntegerField()),
                ('tshirt_size', models.IntegerField(choices=[(4, 'Large'), (5, 'Extra Large'), (2, 'Small'), (3, 'Medium'), (1, 'Extra Small')], default=4)),
                ('is_sc', models.BooleanField(default=False)),
                ('fopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='was_fopper', to='student.Fopper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='USA', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.Fopper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
