# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_leader'),
        ('student', '0003_fopper_leader_parent'),
    ]

    operations = [
    ]
