# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_leader'),
        ('student', '0004_auto_20160910_1602'),
    ]

    operations = [
    ]
