# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_merge_20160910_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='fopper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='was_fopper', to='student.Fopper'),
        ),
        migrations.AddField(
            model_name='leader',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='height_feet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='height_inches',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='huid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='school_type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1),
        ),
        migrations.AddField(
            model_name='leader',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='tshirt_size',
            field=models.IntegerField(choices=[(4, 'Large'), (5, 'Extra Large'), (2, 'Small'), (3, 'Medium'), (1, 'Extra Small')], default=4),
        ),
        migrations.AddField(
            model_name='leader',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fopper',
            name='huid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
