# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20160910_1627'),
        ('student', '0005_merge_20160910_1610'),
    ]

    operations = [
    ]
