# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20160910_1608'),
        ('student', '0007_merge_20160910_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='fopper',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
        ),
    ]
