# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_fopper_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fopper',
            name='preferred_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='swimming_ability',
            field=models.IntegerField(blank=True, choices=[(3, 'Competetive'), (1, 'None'), (2, 'Casual')], null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='preferred_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='switch',
            field=models.BooleanField(default=False),
        ),
    ]
