# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20160910_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fopper',
            name='preferred_difficulty',
        ),
        migrations.AddField(
            model_name='fopper',
            name='fifth_choice',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='first_choice',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='fourth_choice',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='preferred_backpacking_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='preferred_service_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='preferred_switch_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, b'A Trip'), (3, b'C Trip'), (2, b'B Trip')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='second_choice',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='third_choice',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='preferred_trip_type',
            field=models.IntegerField(blank=True, choices=[(2, b'Switch Canoe'), (5, b'Cabin-Based'), (1, b'Backpacking'), (3, b'Switch Service'), (4, b'Site-Based Service')], null=True),
        ),
    ]
