# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20160910_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
