# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20160910_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='fopper',
            name='allergy_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='food_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fopper',
            name='significant_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leader',
            name='allergy_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='food_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='significant_allergy',
            field=models.BooleanField(default=False),
        ),
    ]
