# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_trip_leaders'),
        ('student', '0013_auto_20160911_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fopper',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='fopper',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.DeleteModel(
            name='Fopper',
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
