# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_auto_20160911_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.IntegerField(choices=[(1, b'Email')], default=1)),
                ('category', models.IntegerField(choices=[(1, b'Money')], default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='person.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
